import type { GalleryEntry } from "@/lib/gallery-types";

const DEFAULT_TITLES = [
  "Iteration I",
  "Iteration II",
  "Iteration III",
  "Iteration IV",
  "Iteration V",
] as const;

function iterations(
  sourceSlugs: readonly string[],
  group: GalleryEntry["group"],
  model: GalleryEntry["model"],
) {
  return sourceSlugs.map((sourceSlug, index) => ({
    id: String(index + 1) as GalleryEntry["iterations"][number]["id"],
    title: DEFAULT_TITLES[index],
    sourceSlug,
    thumbnailPath: `/gallery-previews/${group}/${model}/${index + 1}.webp`,
  }));
}

export const galleryManifest: GalleryEntry[] = [
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "union-alpha",
    modelLabel: "Union Alpha",
    sourceDir: "union-alpha-stealth/no-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five anonymous Union Alpha landing generations without a design skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "union-alpha"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "union-alpha",
    modelLabel: "Union Alpha",
    sourceDir: "union-alpha-stealth/taste-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five anonymous Union Alpha landing generations with the taste skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-taste-skill", "union-alpha"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "union-alpha",
    modelLabel: "Union Alpha",
    sourceDir: "union-alpha-stealth/anthropic-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five anonymous Union Alpha landing generations with the frontend-design skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "union-alpha"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "mimo-x-flash-preview",
    modelLabel: "MiMo X Flash",
    sourceDir: "src/variants/with-taste-skill/mimo-x-flash-preview/source",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five MiMo X Flash generations: with taste skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-taste-skill", "mimo-x-flash-preview"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "mimo-x-flash-preview",
    modelLabel: "MiMo X Flash",
    sourceDir: "src/variants/with-design-skill/mimo-x-flash-preview/source",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five MiMo X Flash generations: with design skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "mimo-x-flash-preview"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "mimo-x-flash-preview",
    modelLabel: "MiMo X Flash",
    sourceDir: "src/variants/without-design-skill/mimo-x-flash-preview/source",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five MiMo X Flash generations: without design skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "mimo-x-flash-preview"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "mimo-x-pro-preview",
    modelLabel: "MiMo X Pro",
    sourceDir: "src/variants/with-taste-skill/mimo-x-pro-preview/source",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five MiMo X Pro designs under with taste skill conditions.",
    iterations: iterations(["one","two","three","four","five"], "with-taste-skill", "mimo-x-pro-preview"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "mimo-x-pro-preview",
    modelLabel: "MiMo X Pro",
    sourceDir: "src/variants/with-design-skill/mimo-x-pro-preview/source",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five MiMo X Pro designs under with design skill conditions.",
    iterations: iterations(["1","2","3","4","5"], "with-design-skill", "mimo-x-pro-preview"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "mimo-x-pro-preview",
    modelLabel: "MiMo X Pro",
    sourceDir: "src/variants/without-design-skill/mimo-x-pro-preview/source",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five MiMo X Pro designs under without design skill conditions.",
    iterations: iterations(["one","two","three","four","five"], "without-design-skill", "mimo-x-pro-preview"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "gpt-6-astra-preview",
    modelLabel: "GPT-6 Astra (preview)",
    sourceDir: "src/variants/without-design-skill/gpt-6-astra-preview/source",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-6 Astra (preview) designs from one Codex session at maximum reasoning. Local first attempt with baseline conditions.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "gpt-6-astra-preview"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "gpt-6-astra-preview",
    modelLabel: "GPT-6 Astra (preview)",
    sourceDir: "src/variants/with-design-skill/gpt-6-astra-preview/source",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-6 Astra (preview) designs from one Codex session at maximum reasoning. Local first attempt with frontend-design conditions.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "gpt-6-astra-preview"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "gpt-6-astra-preview",
    modelLabel: "GPT-6 Astra (preview)",
    sourceDir: "src/variants/with-taste-skill/gpt-6-astra-preview/source",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-6 Astra (preview) designs from one Codex session at maximum reasoning. Local first attempt with taste conditions.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-taste-skill", "gpt-6-astra-preview"),
  },
  {
    group: "miscellaneous",
    groupLabel: "With Uncodexify skill",
    model: "gpt-6-astra-preview",
    modelLabel: "GPT-6 Astra (preview)",
    sourceDir: "src/variants/miscellaneous/gpt-6-astra-preview/source",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-6 Astra (preview) designs from one Codex session at maximum reasoning. Local first attempt with uncodixfy conditions.",
    iterations: iterations(["one", "two", "three", "four", "five"], "miscellaneous", "gpt-6-astra-preview"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "composer-1.5",
    modelLabel: "Composer 1.5",
    sourceDir: "with-frontend-design-skill/composer-1.5",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five expressive landing pages with heavier visual direction and per-iteration styling.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "composer-1.5"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "composer-2.0",
    modelLabel: "Composer 2.0",
    sourceDir: "with-frontend-design-skill/composer-2.0",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "A design-forward set of five branded landing explorations built around reusable brain themes.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "composer-2.0"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "composer-2.5",
    modelLabel: "Composer 2.5",
    sourceDir: "composer-2.5-bench/with-frontend-design-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Composer 2.5 design-skill landing generations integrated into the gallery shell.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "composer-2.5"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "fable",
    modelLabel: "Fable 5",
    sourceDir: "fable-with-skill-run",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Fable 5 landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "fable"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "fable-5.1",
    modelLabel: "Fable 5.1",
    sourceDir: "fable-5-1/frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Fable 5.1 design-skill landing generations rendered without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "fable-5.1"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "gemini",
    modelLabel: "Gemini 3.1 Pro",
    sourceDir: "with-frontend-design-skill/gemini",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five interactive marketing pages with motion and a persistent floating switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "gemini"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "gemini-3.5-flash",
    modelLabel: "Gemini 3.5 Flash",
    sourceDir: "gemini-part-dou/next-with-design-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Gemini 3.5 Flash design-skill landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "gemini-3.5-flash"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "grok-4.5",
    modelLabel: "Grok 4.5",
    sourceDir: "grok-4-5-test/nextjs-with-frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Grok 4.5 design-skill landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "grok-4.5"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "grok-4.6",
    modelLabel: "Grok 4.6",
    sourceDir: "grok-4.6-test/frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Grok 4.6 design-skill landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "grok-4.6"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "gpt-5.4",
    modelLabel: "GPT-5.4",
    sourceDir: "with-frontend-design-skill/gpt-5.4",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "A highly art-directed set of five landing concepts with editorial typography and a drawer switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "gpt-5.4"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "gpt-5.5-low",
    modelLabel: "GPT 5.5 low",
    sourceDir: "with-frontend-design-skill/gpt-5.5-low",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT 5.5 low landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "gpt-5.5-low"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "gpt-5.5-high",
    modelLabel: "GPT 5.5 high",
    sourceDir: "with-frontend-design-skill/gpt-5.5-high",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT 5.5 high landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "gpt-5.5-high"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "kimi-k-2.5",
    modelLabel: "Kimi K 2.5",
    sourceDir: "with-frontend-design-skill/kimi-k-2.5",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five client-heavy designs with a floating design switcher and strong visual contrast.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "kimi-k-2.5"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "kimi-k-2.6",
    modelLabel: "Kimi K 2.6",
    sourceDir: "with-frontend-design-skill/kimi-k-2.6",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five client-heavy designs with a floating design switcher and strong visual contrast.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "kimi-k-2.6"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "kimi-k3",
    modelLabel: "Kimi K3",
    sourceDir: "kimi-k3/anthropic-frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Kimi K3 design-skill landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "kimi-k3"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "opus-4.6",
    modelLabel: "Opus 4.6",
    sourceDir: "with-frontend-design-skill/opus-4.6/second-brain",
    sourceAppType: "vite",
    defaultIteration: "1",
    summary: "A Vite-based set of five animated routes ported into the unified gallery runtime.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "opus-4.6"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "opus-4.7",
    modelLabel: "Opus 4.7",
    sourceDir: "with-frontend-design-skill/opus-4.7",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five editorial-to-zen landing explorations for a second-brain app, integrated without the original floating switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "opus-4.7"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "opus-4.8",
    modelLabel: "Opus 4.8",
    sourceDir: "opus-4.8-test/with-anthropic-design-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Opus 4.8 design-skill landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "opus-4.8"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "glm-5-turbo",
    modelLabel: "GLM 5 Turbo",
    sourceDir: "with-frontend-design-skill/glm-5-turbo",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Cortex landing explorations with a dynamic route and per-iteration visual systems.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "glm-5-turbo"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "glm-5.1",
    modelLabel: "GLM 5.1",
    sourceDir: "with-frontend-design-skill/glm-5.1",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five named routes (Neural Ink through Retro Terminal) with strong typography and atmosphere.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "glm-5.1"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "glm-5.2",
    modelLabel: "GLM 5.2",
    sourceDir: "glm5-2/glm-anthropic-frontend-design-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GLM 5.2 design-skill Marginalia landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "glm-5.2"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "sonnet-5",
    modelLabel: "Sonnet 5",
    sourceDir: "sonnet-bench/nextjs-anthropic-frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Sonnet 5 design-skill landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "sonnet-5"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "fable",
    modelLabel: "Fable 5",
    sourceDir: "fable-test-taste-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Fable 5 landing generations produced with the taste skill and integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-taste-skill", "fable"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "fable-5.1",
    modelLabel: "Fable 5.1",
    sourceDir: "fable-5-1/design-taste",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Fable 5.1 taste-skill landing generations rendered without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-taste-skill", "fable-5.1"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "grok-4.5",
    modelLabel: "Grok 4.5",
    sourceDir: "grok-4-5-test/nextjs-with-taste-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Grok 4.5 taste-skill landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-taste-skill", "grok-4.5"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "grok-4.6",
    modelLabel: "Grok 4.6",
    sourceDir: "grok-4.6-test/taste-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Grok 4.6 taste-skill landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-taste-skill", "grok-4.6"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "kimi-k3",
    modelLabel: "Kimi K3",
    sourceDir: "kimi-k3/design-taste-frontend",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Kimi K3 taste-skill landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-taste-skill", "kimi-k3"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "glm-5.2",
    modelLabel: "GLM 5.2",
    sourceDir: "glm5-2/glm-design-taste-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GLM 5.2 taste-skill Marginalia landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-taste-skill", "glm-5.2"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "sonnet-5",
    modelLabel: "Sonnet 5",
    sourceDir: "sonnet-bench/nextjs-taste-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Sonnet 5 taste-skill landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-taste-skill", "sonnet-5"),
  },
  {
    group: "with-ui-sh-skill",
    groupLabel: "With UI SH Skill",
    model: "composer-2.0",
    modelLabel: "Composer 2.0",
    sourceDir: "ui-sh-test/composer-2",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Composer 2.0 UI-SH landing generations integrated into the gallery shell.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-ui-sh-skill", "composer-2.0"),
  },
  {
    group: "with-ui-sh-skill",
    groupLabel: "With UI SH Skill",
    model: "gpt-5.5-low",
    modelLabel: "GPT 5.5 low",
    sourceDir: "ui-sh-test/gpt-5.5",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT 5.5 low UI-SH landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-ui-sh-skill", "gpt-5.5-low"),
  },
  {
    group: "with-ui-sh-skill",
    groupLabel: "With UI SH Skill",
    model: "gpt-5.5-high",
    modelLabel: "GPT 5.5 high",
    sourceDir: "ui-sh-test/gpt-5.5-high",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT 5.5 high UI-SH landing generations from a Pages Router source app.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-ui-sh-skill", "gpt-5.5-high"),
  },
  {
    group: "with-ui-sh-skill",
    groupLabel: "With UI SH Skill",
    model: "opus-4.7",
    modelLabel: "Opus 4.7",
    sourceDir: "ui-sh-test/opus-4.7",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Opus 4.7 UI-SH landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-ui-sh-skill", "opus-4.7"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "composer-1.5",
    modelLabel: "Composer 1.5",
    sourceDir: "without-frontend-design-skill/composer-1.5",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "A plainer five-page set with a shared switcher and lighter design experimentation.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "composer-1.5"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "composer-2.0",
    modelLabel: "Composer 2.0",
    sourceDir: "without-frontend-design-skill/composer-2.0",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five route-grouped landing pages with a shared floating iteration switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "composer-2.0"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "composer-2.5",
    modelLabel: "Composer 2.5",
    sourceDir: "composer-2.5-bench/without-frontend-design-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Composer 2.5 baseline landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "composer-2.5"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "fable",
    modelLabel: "Fable 5",
    sourceDir: "fable-test-run",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Fable 5 baseline landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "fable"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "fable-5.1",
    modelLabel: "Fable 5.1",
    sourceDir: "fable-5-1/no-skills",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Fable 5.1 baseline landing generations rendered without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "fable-5.1"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "gemini",
    modelLabel: "Gemini 3.1 Pro",
    sourceDir: "without-frontend-design-skill/gemini",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five simple but distinct landing pages navigated through a lightweight client navigation component.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "gemini"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "gemini-3.5-flash",
    modelLabel: "Gemini 3.5 Flash",
    sourceDir: "gemini-part-dou/next-without-design-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Gemini 3.5 Flash baseline landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "gemini-3.5-flash"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "grok-4.5",
    modelLabel: "Grok 4.5",
    sourceDir: "grok-4-5-test/nextjs-without-frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Grok 4.5 baseline landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "grok-4.5"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "grok-4.6",
    modelLabel: "Grok 4.6",
    sourceDir: "grok-4.6-test/no-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Grok 4.6 baseline landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "grok-4.6"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "gpt-5.4",
    modelLabel: "GPT-5.4",
    sourceDir: "without-frontend-design-skill/gpt-5.4",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five routes with a local iteration switcher and lighter polish than the design-skill version.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "gpt-5.4"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "gpt-5.5-low",
    modelLabel: "GPT 5.5 low",
    sourceDir: "without-frontend-design-skill/gpt-5.5-low",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT 5.5 low landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "gpt-5.5-low"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "gpt-5.5-high",
    modelLabel: "GPT 5.5 high",
    sourceDir: "without-frontend-design-skill/gpt-5.5-high",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT 5.5 high landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "gpt-5.5-high"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "kimi-k-2.5",
    modelLabel: "Kimi K 2.5",
    sourceDir: "without-frontend-design-skill/kimi-k-2.5",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five designs grouped under a shared layout and floating switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "kimi-k-2.5"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "kimi-k-2.6",
    modelLabel: "Kimi K 2.6",
    sourceDir: "without-frontend-design-skill/kimi-k-2.6",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five baseline landing pages with lighter polish and a shared in-app iteration switcher removed for the gallery shell.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "kimi-k-2.6"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "kimi-k3",
    modelLabel: "Kimi K3",
    sourceDir: "kimi-k3/no-design-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Kimi K3 baseline landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "kimi-k3"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "opus-4.6",
    modelLabel: "Opus 4.6",
    sourceDir: "without-frontend-design-skill/opus-4.6",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five conventional routes with a persistent switcher and a more restrained visual baseline.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "opus-4.6"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "opus-4.7",
    modelLabel: "Opus 4.7",
    sourceDir: "without-frontend-design-skill/opus-4.7",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five quieter landing-page iterations for a second-brain product, presented without the source app's floating switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "opus-4.7"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "opus-4.8",
    modelLabel: "Opus 4.8",
    sourceDir: "opus-4.8-test/without-anthropic-design-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Opus 4.8 baseline landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "opus-4.8"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "glm-5-turbo",
    modelLabel: "GLM 5 Turbo",
    sourceDir: "without-frontend-design-skill/glm-5-turbo",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five numbered designs with a shared minimalist-to-bold range and a route-based switcher in the source app.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "glm-5-turbo"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "glm-5.1",
    modelLabel: "GLM 5.1",
    sourceDir: "without-frontend-design-skill/glm-5.1",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five straightforward routes with varied layouts and gradients, tuned for the gallery without the in-app switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "glm-5.1"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "glm-5.2",
    modelLabel: "GLM 5.2",
    sourceDir: "glm5-2/glm-no-frontend-design-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GLM 5.2 baseline Pages Router landing generations integrated without the source app's local switcher.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "glm-5.2"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "sonnet-5",
    modelLabel: "Sonnet 5",
    sourceDir: "sonnet-bench/nextjs-no-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Sonnet 5 baseline landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "sonnet-5"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "sol",
    modelLabel: "GPT-5.6 Sol",
    sourceDir: "gpt-5-6-test/sol/anthropic-frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-5.6 Sol max-reasoning generations produced with the frontend-design skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "sol"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "sol",
    modelLabel: "GPT-5.6 Sol",
    sourceDir: "gpt-5-6-test/sol/design-taste",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-5.6 Sol max-reasoning generations produced with the taste skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-taste-skill", "sol"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "sol",
    modelLabel: "GPT-5.6 Sol",
    sourceDir: "gpt-5-6-test/sol/no-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-5.6 Sol max-reasoning baseline generations produced without a design skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "sol"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "luna",
    modelLabel: "GPT-5.6 Luna",
    sourceDir: "gpt-5-6-test/luna/anthropic-frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-5.6 Luna max-reasoning generations produced with the frontend-design skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "luna"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "luna",
    modelLabel: "GPT-5.6 Luna",
    sourceDir: "gpt-5-6-test/luna/design-taste",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-5.6 Luna max-reasoning generations produced with the taste skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-taste-skill", "luna"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "luna",
    modelLabel: "GPT-5.6 Luna",
    sourceDir: "gpt-5-6-test/luna/no-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-5.6 Luna max-reasoning baseline generations produced without a design skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "luna"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "terra",
    modelLabel: "GPT-5.6 Terra",
    sourceDir: "gpt-5-6-test/terra/anthropic-frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-5.6 Terra max-reasoning generations produced with the frontend-design skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "terra"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "terra",
    modelLabel: "GPT-5.6 Terra",
    sourceDir: "gpt-5-6-test/terra/design-taste",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-5.6 Terra max-reasoning generations produced with the taste skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-taste-skill", "terra"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "terra",
    modelLabel: "GPT-5.6 Terra",
    sourceDir: "gpt-5-6-test/terra/no-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-5.6 Terra max-reasoning baseline generations produced without a design skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "terra"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "muse-spark-1.2",
    modelLabel: "Muse Spark 1.2",
    sourceDir: "muse-spark-test/next-frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Muse Spark 1.2 landing generations produced with the frontend-design skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "muse-spark-1.2"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "muse-spark-1.2",
    modelLabel: "Muse Spark 1.2",
    sourceDir: "muse-spark-test/next-design-taste",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Muse Spark 1.2 landing generations produced with the taste skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-taste-skill", "muse-spark-1.2"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "muse-spark-1.2",
    modelLabel: "Muse Spark 1.2",
    sourceDir: "muse-spark-test/next-no-skills",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Muse Spark 1.2 baseline landing generations produced without a design skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "muse-spark-1.2"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "opus-5",
    modelLabel: "Opus 5",
    sourceDir: "opus-cc-test/next-anthropic-frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Opus 5 design-skill landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "opus-5"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "opus-5",
    modelLabel: "Opus 5",
    sourceDir: "opus-cc-test/next-design-taste-frontend",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Opus 5 taste-skill landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-taste-skill", "opus-5"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "opus-5",
    modelLabel: "Opus 5",
    sourceDir: "opus-cc-test/next-no-skills",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Opus 5 baseline landing generations integrated without the source app's local switcher.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "opus-5"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "gemini-3.7-flash",
    modelLabel: "Gemini 3.7 Flash",
    sourceDir: "gemini-3.7-flash/frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Gemini 3.7 Flash landing generations produced with the frontend-design skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "gemini-3.7-flash"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "gemini-3.7-flash",
    modelLabel: "Gemini 3.7 Flash",
    sourceDir: "gemini-3.7-flash/design-taste",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Gemini 3.7 Flash landing generations produced with the taste skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-taste-skill", "gemini-3.7-flash"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "gemini-3.7-flash",
    modelLabel: "Gemini 3.7 Flash",
    sourceDir: "gemini-3.7-flash/no-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Gemini 3.7 Flash baseline landing generations produced without a design skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "gemini-3.7-flash"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "glm-5.3-flash",
    modelLabel: "GLM 5.3 Flash",
    sourceDir: "ox-alpha-bench/nextjs-frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GLM 5.3 Flash landing generations from its anonymous Ox Alpha run with the frontend-design skill.",
    iterations: iterations(
      ["1", "2", "3", "4", "5"],
      "with-design-skill",
      "glm-5.3-flash",
    ),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "glm-5.3-flash",
    modelLabel: "GLM 5.3 Flash",
    sourceDir: "ox-alpha-bench/nextjs-taste-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GLM 5.3 Flash landing generations from its anonymous Ox Alpha run with the taste skill.",
    iterations: iterations(
      ["one", "two", "three", "four", "five"],
      "with-taste-skill",
      "glm-5.3-flash",
    ),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "glm-5.3-flash",
    modelLabel: "GLM 5.3 Flash",
    sourceDir: "ox-alpha-bench/nextjs-plain",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five baseline GLM 5.3 Flash landing generations from its anonymous Ox Alpha run without a design skill.",
    iterations: iterations(
      ["1", "2", "3", "4", "5"],
      "without-design-skill",
      "glm-5.3-flash",
    ),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "gemini-3.8-flash",
    modelLabel: "Gemini 3.8 Flash",
    sourceDir: "gemini-3.8-flash/with-frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Gemini 3.8 Flash landing generations produced with the frontend-design skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "gemini-3.8-flash"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "gemini-3.8-flash",
    modelLabel: "Gemini 3.8 Flash",
    sourceDir: "gemini-3.8-flash/with-design-taste",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Gemini 3.8 Flash landing generations produced with the taste skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-taste-skill", "gemini-3.8-flash"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "gemini-3.8-flash",
    modelLabel: "Gemini 3.8 Flash",
    sourceDir: "gemini-3.8-flash/no-skills",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Gemini 3.8 Flash baseline landing generations produced without a design skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "gemini-3.8-flash"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "muse-spark-1.3",
    modelLabel: "Muse Spark 1.3",
    sourceDir: "muse-spark-1.3/next-frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Muse Spark 1.3 landing generations produced with the frontend-design skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-design-skill", "muse-spark-1.3"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "muse-spark-1.3",
    modelLabel: "Muse Spark 1.3",
    sourceDir: "muse-spark-1.3/next-design-taste",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Muse Spark 1.3 landing generations produced with the taste skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-taste-skill", "muse-spark-1.3"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "muse-spark-1.3",
    modelLabel: "Muse Spark 1.3",
    sourceDir: "muse-spark-1.3/next-clean",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five Muse Spark 1.3 baseline landing generations produced without a design skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "muse-spark-1.3"),
  },
  {
    group: "miscellaneous",
    groupLabel: "With Uncodexify skill",
    model: "gpt-5.4",
    modelLabel: "GPT-5.4",
    sourceDir: "with-uncodexify-skill/gpt-5.4",
    sourceAppType: "next",
    defaultIteration: "1",
    summary:
      "These screens were produced with the Uncodexify skill (not the frontend design skill): five Commonplace-themed landings from GPT-5.4, integrated here without the original in-app route switcher.",
    iterations: [
      {
        id: "1",
        title: "Workspace",
        sourceSlug: "1",
        thumbnailPath: "/gallery-previews/miscellaneous/gpt-5.4/preview.webp",
      },
      {
        id: "2",
        title: "Library",
        sourceSlug: "2",
        thumbnailPath: "/gallery-previews/miscellaneous/gpt-5.4/preview.webp",
      },
      {
        id: "3",
        title: "Desk",
        sourceSlug: "3",
        thumbnailPath: "/gallery-previews/miscellaneous/gpt-5.4/preview.webp",
      },
      {
        id: "4",
        title: "Search",
        sourceSlug: "4",
        thumbnailPath: "/gallery-previews/miscellaneous/gpt-5.4/preview.webp",
      },
      {
        id: "5",
        title: "Review",
        sourceSlug: "5",
        thumbnailPath: "/gallery-previews/miscellaneous/gpt-5.4/preview.webp",
      },
    ],
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "gpt-6-astra",
    modelLabel: "GPT-6 Astra",
    sourceDir: "astra-6/frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-6 Astra frontend-design landing generations with original typography and interactive notebooks.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "gpt-6-astra"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "gpt-6-astra",
    modelLabel: "GPT-6 Astra",
    sourceDir: "astra-6/design-taste",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-6 Astra design-taste landing generations with original typography and interactive notebooks.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-taste-skill", "gpt-6-astra"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "gpt-6-astra",
    modelLabel: "GPT-6 Astra",
    sourceDir: "astra-6/no-skills",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five GPT-6 Astra no-skills landing generations with original typography and interactive notebooks.",
    iterations: iterations(["one", "two", "three", "four", "five"], "without-design-skill", "gpt-6-astra"),
  },
  {
    group: "with-design-skill",
    groupLabel: "With Design Skill",
    model: "swe-2",
    modelLabel: "SWE-2",
    sourceDir: "swe-bench/frontend-design",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five SWE-2 Commonplace landing generations produced with the frontend-design skill.",
    iterations: iterations(["one", "two", "three", "four", "five"], "with-design-skill", "swe-2"),
  },
  {
    group: "with-taste-skill",
    groupLabel: "With Taste Skill",
    model: "swe-2",
    modelLabel: "SWE-2",
    sourceDir: "swe-bench/taste-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five SWE-2 Commonplace landing generations produced with the taste skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "with-taste-skill", "swe-2"),
  },
  {
    group: "without-design-skill",
    groupLabel: "Without Design Skill",
    model: "swe-2",
    modelLabel: "SWE-2",
    sourceDir: "swe-bench/no-skill",
    sourceAppType: "next",
    defaultIteration: "1",
    summary: "Five SWE-2 Engram baseline landing generations produced without a design skill.",
    iterations: iterations(["1", "2", "3", "4", "5"], "without-design-skill", "swe-2"),
  },
];

export function getGalleryEntry(group: string, model: string) {
  return galleryManifest.find((entry) => entry.group === group && entry.model === model);
}
